name: Workflow for incremental update
  #on: [push]
on:
  workflow_dispatch:
  schedule:
    - cron: '30 17 * * 5'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Run incremental changes
      run: python main.py
      env:
        SENDER: ${{ secrets.SENDER }}
        RECEIVER: ${{ secrets.RECEIVER }}
        SERVER_DETAILS: ${{ secrets.SERVER_DETAILS }}
        PWORD: ${{ secrets.PWORD }}
        PORT: ${{ secrets.PORT }}
    - name: Commit changes to main branch
      run: |      
        git config --global user.email "nonactive@gmail.com"
        git config --global user.name "M12 Incremental"
        now=$(date)
        git add .
        git commit -m "M12 product changes as of '$now'"
        git push origin main
